### PR TITLE
VirtualBox appliance generation: Change nic mode, delete temporary files and rename conflicting directory

### PR DESCRIPTION
**Pull request by Valtis**
VirtualBox uses a directory under /tmp for ipc. This can cause issues
if user already has VirtualBox installed, as the directory may already
exist and may be owned by root. The directory is renamed to avoid any
name collisions.

The VirtualBox working directory is also deleted, as this gets published, which is not intended.

Finally VirtualBox NIC is configured to use bridged mode instead of the default NAT, as this makes connecting to the VM easier from the host machine.

Signed-off-by: Erkka Kääriä <erkka.kaaria@intel.com>

### CODE REVIEW

**Comment by Valtis** [comment]
@igor-stoppa Does this look good for you?

**Comment by kad** [comment]
not good from my point of view. Two simultaneous builds on same host might mess with each other.
Why not to use mktemp and directory name pass via env variable or something like this ?

**Comment by igor-stoppa** [comment]
yes, we just discussed this and agreed to have a unique id in the file name
(ex: bitbake pid)

On 11 May 2016 at 14:26, Alexander D. Kanevskiy <notifications@github.com>
wrote:

> not good from my point of view. Two simultaneous builds on same host might
> mess with each other.
> Why not to use mktemp and directory name pass via env variable or
> something like this ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ostroproject/meta-ostro/pull/178#issuecomment-218432303>
>



-- 
igor

**Comment by Valtis** [comment]
Round 2. It turns out you can pass the directory name through environmental variable, so I dropped the patch as long as we are OK that the directory resides under /tmp (that is hardcoded).

Also some whitespace fixes, as my editor ate some unnecessary whitespace. I noticed this only after pushing the changes. I'll fix it if it is an issue.

**Comment by igor-stoppa** [comment]
Nitpicking: in the rm phase I would reuse the variable, if it's still available, instead of its string value.

**Comment by igor-stoppa** [comment]
@Valtis: I am confused by the comment "It turns out you can pass the directory name through environmental variable" when then you remove a file. To which directory are you referring to?

**Comment by Valtis** [comment]
Updated PR.

I mean the temporary directory VirtualBox creates under /tmp (/tmp/.vbox-......-ipc/files here)

**Comment by igor-stoppa** [comment]
codewise LGTM  +1, spaces aside

for the spaces, I could close an eye, anyway this patch doesn't go anywhere

**Comment by Valtis** [comment]
retest this please

Edison timed out during flashing.

**Comment by Valtis** [comment]
Working directory is now deleted, as this gets published with the images. The appliance is also now configured to use bridged networking instead of using NAT, as this makes connecting to the VM easier.

**Comment by igor-stoppa** [comment]
@Valtis looks good, maybe you could reword the title of the PR, to highlight that there are also these 2 new changes.

**Comment by pohly** [comment]
Edison tests failed to run. Merging anyway.

**Pull request merged**
