### PR TITLE
Enable Soletta C tests and FBP tests as ptest:

### PR DESCRIPTION
**Pull request by otcyanglei**
add inc file and update bbapend file for Soletta C/FBP test files compiling and installation
    patch fbp-run-tests to meet the ptest result output format
    add run-ptest as ptest execution entry

Signed-off-by: Lei Yang <lei.a.yang@intel.com>

### CODE REVIEW

**Comment by kad** [comment]
ok to test

**Comment by otcyanglei** [comment]
@mythi 
QA team is going to run soletta tests in dev image. This patch is for this purpose. Could you review and merge this PR?

**Comment by mythi** [comment]
proposed to move to meta-soletta.

**Comment by otcyanglei** [comment]
Thanks, Mikko, I am going to try to submit patches to Soletta and meta-soletta upstream. 
And will use /bin/sh to replace /bin/bash too.

**Pull request closed without merging**
