### PR TITLE
system-and-security-architecture.rst: remove TODO keyword

### PR DESCRIPTION
**Pull request by pohly**
Having "TODO" in the documentation was called out as a release
blocker. Let's use this PR to discuss how we can handle that properly.

[skip ci]

### CODE REVIEW

**Comment by ipuustin** [comment]
I think this looks good. I would perhaps merge the two last commits. I also think that the TODOs make sense for the features that are not present yet in the distribution. Other than the TODO items, the documentation should reflect the current distribution state in the same repository.

**Comment by kad** [comment]
I like usage of TODO as a keyword. Easy to search for things that shall be written.
It gives impression that "we care about this thing, but not yet done", rather than "nobody cares about this missing bit/aspect/corner case".

**Comment by pohly** [comment]
On Tue, 2016-03-01 at 00:24 -0800, Ismo Puustinen wrote:
> I also think that the TODOs make sense for the features that are not
> present yet in the distribution.

So would you keep those TODO items in the documentation?

**Comment by pohly** [comment]
On Tue, 2016-03-01 at 00:24 -0800, Ismo Puustinen wrote:
> I think this looks good. I would perhaps merge the two last commits.

I have intentionally not done that because the "remove resolved TODO
items" can be accepted permanently (items are resolved after all),
whereas "avoid using TODO keyword" is just (temporarily?) avoiding the
keyword for the release. We might accept that change and then revert it
again after the release.

**Comment by kad** [comment]
Table of Content items, like below, I'd  keep to show potential readers that documentation is coming.
```
*TODO*: system provisioning and first boot security
```

For rest of TODO usages I have no any strong opinion.

**Comment by dbkinder** [comment]
I helped Rajesh Sapra edit this document to remove TODOs for publishing to the website.

**Comment by pohly** [comment]
Rebased onto current master.

I've reverted the changes introduced by PR #11 because they are partially incorrect. Some of my fixes were not included, so this PR still has them.

I removed the global TODO removal because these markers are useful. Let's merge this PR *after* the release and then rethink how we handle such markers going forward.

**Comment by dbkinder** [comment]
We can merge this after the small tweaks we discussed on email are fixed.

**Comment by kad** [comment]
@pohly @dbkinder so, what is the state of this PR ? if needed to be updated, let's update/rebase.

**Comment by pohly** [comment]
Do not merge, this has to be rebased and needs further work - will do as soon as time permits.

**Comment by pohly** [comment]
Revised commits pushed, @dbkinder please review.

**Comment by mythi** [comment]
+1

**Comment by dbkinder** [comment]
+1

**Pull request merged**
