### PR TITLE
Update the 802.15.4 radio boards assembly picture for Galileo boards

### PR DESCRIPTION
**Pull request by yongli3**
Using different colors for cables, and Add pin definitions

[skip ci]

Signed-off-by: Yong Li <yong.b.li@intel.com>

### CODE REVIEW

**Comment by yongli3** [comment]
@neofang @mythi @barbieri @wzhen12 @peijiajames please help to review

**Comment by mythi** [comment]
@dbkinder please check this fits on the page.

**Comment by dbkinder** [comment]
The image fits on the page fine (there's a :width: 350px tag that addresses that in the .rst file).  However, the pin definition labels added to the picture are impossibly small to read.  I'll send @yongli3 a cropped version of this image that's a closeup of the pin labels to incorporate into the document.  Let me know if there's not enough time to wait @mythi and you can merge this as is and I'll fix it in a new PR.

**Comment by yongli3** [comment]
@dbkinder I just added the new closeup image as your described, please check it.

Regarding the pin define in the original at86rf212-galileo.png, I can read it clearly by clicking on the image two times

**Comment by dbkinder** [comment]
+1 looks great. With just the original image, I wouldn't know the pins were labelled (it's pretty subtle).  With both images there now, it's much clearer.  Thanks!

**Comment by barbieri** [comment]
+1, very good!

**Comment by dbkinder** [comment]
This is ready for merge @pohly

**Pull request merged**
