### PR TITLE
ostro.conf updates

### PR DESCRIPTION
**Pull request by mythi**
This PR removes some of the recipes from world build.

As we are now building the whole world for eSDK, we need to review
what are the recipes that are actually needed/useful.

With meta-openembedded layers (and some others too) we use
whitelist.bbclass to select which recipes are needed. However,
with openembedded-core, PNBLACKLIST is suited better.

This commit blacklists some recipes from openembedded-core that are
not applicable for Ostro.

Some further optimization is still needed. This should give a
safe start.

### CODE REVIEW

**Comment by mythi** [comment]
v2: removed tempered as well since it depends on hid-api

**Comment by mythi** [comment]
v3: rebased and force pushed with some updates

**Comment by mythi** [comment]
v4: rebased, added 2bbf27c

**Comment by mythi** [comment]
@pohly @ipuustin can you take a look please?

**Comment by ipuustin** [comment]
Do you have a particular reason for not using `git revert`?

**Comment by mythi** [comment]
@ipuustin no particular reason. it was quicker and less error prone this way since the revert conflict was messy.

**Comment by ipuustin** [comment]
@mythi : Ok, that's a good enough reason. Otherwise the changes look good to me.

**Comment by mythi** [comment]
v5: added 01df7ed: this helps making os-core leaner. The build was failing so added a new commit in this PR.

**Comment by pohly** [comment]
+1 for merging, although I think that an explanation why some components are "not preferred" would be useful. I know that it is because of concerns about the upstream maintenance status, but others do not know that.

**Comment by mythi** [comment]
v6: force pushed updates to commit messages based on feedback

**Pull request merged**
