### PR TITLE
ostro-image.bb : Add qatests feature only in dev image

### PR DESCRIPTION
**Pull request by daweiwu**
QA needs some package/app for some test cases just enabled in dev image,
so use qatests feature and remove qatests from IMAGE_FEATURES

### CODE REVIEW

**Comment by kad** [comment]
ok to test

**Comment by daweiwu** [comment]
Please see the package group in https://github.com/ostroproject/meta-iotqa/pull/15

**Comment by daweiwu** [comment]
@mythi ,  is it OK to merge this ?

**Comment by mythi** [comment]
No. The build fails because the packagegroup is not there.

**Comment by daweiwu** [comment]
Thanks for the info , I know the reason. It depends on https://github.com/ostroproject/meta-iotqa/pull/15 which is not merged yet .

**Comment by daweiwu** [comment]
https://github.com/ostroproject/meta-iotqa/pull/15 was merged  and the package group is there in meta-iotqa . @mythi , could you help to pull the latest meta-iotqa and merge this one ? Then CI can test this again ?  I have tested them , no any issue for image building. Thanks.

**Comment by mythi** [comment]
There's still no agreement to add the sample apps in the image. I support what mps thinks. 

Closing this until there's a consensus.

**Comment by daweiwu** [comment]
@mythi , per to the mail discussion , can we reopen and merge this ?

**Comment by mythi** [comment]
@daweiwu OK, but please rebase

**Comment by daweiwu** [comment]
@mythi , is that OK now ?

**Comment by daweiwu** [comment]
Let's see if CI has build issue with this.

**Comment by daweiwu** [comment]
@mythi , image building/flashing are OK (CI fails at test_edsion seems due to unknown reason since  the serial log of it is not complete) , so could you help to merge this ? Thanks.

**Pull request merged**
