### PR TITLE
soletta: Enable Node.js bindings by default

### PR DESCRIPTION
**Pull request by nagineni**
This enables Node.js bindings by default.

[1] https://github.com/solettaproject/meta-soletta/pull/71 
[2] This 
[3] https://github.com/ostroproject/meta-iot-web/pull/10

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by nagineni** [comment]
@mythi @brunobottazzini @barbieri Could you please have a look?

**Comment by nagineni** [comment]
Changes from solettaproject/meta-soletta#63 are needed to make the build pass.

**Comment by mythi** [comment]
@nagineni +1. Let's wait for meta-soletta changes first.

**Comment by nagineni** [comment]
Test build: https://ostroproject.org/jenkins/job/ostro-os_pull-requests/412/

**Comment by brunobottazzini** [comment]
+1

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
@nagineni please rebase this

**Pull request merged**
