### PR TITLE
avahi: enablers for adding avahi

### PR DESCRIPTION
**Pull request by ipuustin**
1. remove libnss-mdns dependency
2. enable `libdns_sd` support
3. add firewall support

### CODE REVIEW

**Comment by kad** [comment]
👍

**Comment by pohly** [comment]
Also looks good to me. Does this add new components to the build?

If so, it would be interesting to merge PR #186 first and use this PR here as testcase, but PR #186 needs some further work and discussion and I don't want to delay this PR here unnecessarily.

**Comment by ipuustin** [comment]
Rebased and fixed a copy-paste error in firewall command. @pohly, no components are added to the build. However, if some image requires avahi, it should now work properly in Ostro.

**Comment by ipuustin** [comment]
Added one header that I forgot to install.

**Comment by ipuustin** [comment]
retest me please

**Comment by ipuustin** [comment]
retest this please

**Pull request merged**
