### PR TITLE
ostro_security_flags.inc: removing soletta exception for Wformat flags

### PR DESCRIPTION
**Pull request by ereshetova**
Signed-off-by: Elena Reshetova <elena.reshetova@intel.com>

### CODE REVIEW

**Comment by pohly** [comment]
Some comment in the commit message explaining that there was no real reason for weakening the compile flags and that compiling with the flags enabled is better (and works) would be nice. But don't bother unless you want to, updating the commit is not required.

**Comment by ereshetova** [comment]
Test Edison failed, but I doubt it is related by any means to this...

**Comment by kad** [comment]
retest this please

**Comment by ereshetova** [comment]
now test_beagleboneblack failed with similar output...

**Comment by pohly** [comment]
retest this please

The latest Beaglebone tests (in other PRs) were all successful again. Let's see...

**Comment by pohly** [comment]
@ereshetova looks like you need to rebase, it now fails to apply cleanly.

**Pull request closed without merging**
