### PR TITLE
swupd-client_%.bbappend: configure swupd repo URLs

### PR DESCRIPTION
**Pull request by rojkov**
By default swupd checks for updates at http://example.com
and in case of fetching from an HTTPS URL it uses a
pre-defined public key which is specific to ClearLinux.

This patch configures meta-ostro to use Ostro's public
repository for software updates by default.

Fixes: IOTOS-1754

NB: Depends on https://lists.yoctoproject.org/pipermail/yocto/2016-August/031680.html accepted to meta-swupd.

### CODE REVIEW

**Comment by mythi** [comment]
the dependencies are now in master so let's re-trigger and check the output.

retest this please

**Comment by kad** [comment]
Should we do similar PR to ostro-os-xt ?

**Comment by mythi** [comment]
@kad we have ostroproject/ostro-os-xt/pull/8 already. We may need to take the meta-swupd fix in the bbappend too however.

**Comment by kad** [comment]
ah, ok, missed that.

**Comment by mythi** [comment]
@rojkov could you check the resulting images?

**Comment by rojkov** [comment]
@mythi at least `swupd check-update` works as expected

```
root@intel-corei7-64:~# swupd check-update
swupd-client software update checker 3.6.0
   Copyright (C) 2012-2016 Intel Corporation

Querying server version.
Attempting to download version string to memory
There are no updates available
```

And `swupd verify` fails as expected too, because updates for PR are not published

```
root@intel-corei7-64:~# swupd verify
swupd-client software verify 3.6.0
   Copyright (C) 2012-2016 Intel Corporation

Verifying version 16340
Attempting to download version string to memory
Failed to retrieve 16340 MoM manifest
Unable to download/verify 16340 Manifest.MoM
Possible filedescriptor leak: fd_number="3",fd_details="/dev/urandom"
Error: Verify did not fully succeed
```

No more "bad certificate" errors.

**Comment by mythi** [comment]
@rojkov thanks for checking! merging

**Pull request merged**
