### PR TITLE
booting-and-installation.rst: add Galileo instructions and minor updates

### PR DESCRIPTION
**Pull request by gvancuts**
- Add instructions for running Ostro OS images on the
Intel Galileo Gen 2 platform
- Update image file format (now compressed with xz) and adjust instructions
accordingly

[skip ci]

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

### CODE REVIEW

**Comment by gvancuts** [comment]
I did not realise I was working off an outdated meta-ostro/mater. Will fix and force-push

**Comment by gvancuts** [comment]
The merge conflict has been resolved, can you please take a look

@pohly @mythi @kad @dbkinder

**Comment by pohly** [comment]
Looks good at a quick glance except for this one incomplete sentence ("as root at").

**Comment by kad** [comment]
Let's resolve @pohly comment, and I'll merge it.

**Comment by gvancuts** [comment]
Force-pushed an updated version that addresses comments from both @pohly and @dbkinder

**Pull request merged**
