### PR TITLE
swupd: Disable boot file heuristics

### PR DESCRIPTION
**Pull request by rojkov**
Ostro uses a mechanism different from what's used in ClearLinux
to detect changes in kernel, bootloader, initramfs.
    
This commit disables the CLR specific mechanism by commenting
out a call to boot file heuristics.
    
Fixes: IOTOS-1357

Original PR https://github.com/otcshare/meta-iot-os/pull/242

### CODE REVIEW

**Comment by kad** [comment]
retest it please

**Comment by kad** [comment]
retest this please

**Comment by pohly** [comment]
Is "retest it please" another magic phrase for our CI system, or a request for some real person?

**Comment by kad** [comment]
yes, it's another magic keywords that available when jenkins and github integrated with webhooks publicly.

**Comment by kad** [comment]
test this please

**Pull request closed without merging**
