### PR TITLE
ostroproject-ci.inc: defaults to be used by CI

### PR DESCRIPTION
**Pull request by kad**
This set of commits adjusts default parameters that are used inside Ostro Project CI

Obsoletes PR #50

### CODE REVIEW

**Comment by kad** [comment]
attn @okartau

**Comment by okartau** [comment]
Looks good, but has to be tried in real build path

**Comment by mythi** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by kad** [comment]
retest this please

**Comment by mythi** [comment]
+1, builds good except edison testing. taking.

**Pull request merged**
