### PR TITLE
DOC: Fix incorrect use of ::: for code blocks

### PR DESCRIPTION
**Pull request by dbkinder**
Scanned through all .rst files to change incorrect code block
ReST tag shorthand from ":::" to "::"  (settled on using "::" vs. ": ::" consistently)
and force pushed.

[skip ci]

Signed-off-by: David Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by pohly** [comment]
In PR #156 Geoffroy just just two colons directly after the last word. Wouldn't it be better to use that style consistently? Or are there reasons to use ": ::" instead?

**Comment by gvancuts** [comment]
In PR #156<https://github.com/ostroproject/meta-ostro/pull/156> Geoffroy just just two colons directly after the last word. Wouldn't it be better to use that style consistently? Or are there reasons to use ": ::" instead?

As far as I know there is no difference but I would also prefer that we stay consistent and use "::". I opted for "::" earlier because that's already how it's done elsewhere in our documentation.

**Comment by dbkinder** [comment]
I wanted the sentence preceding the block to have a ":" at the end indicating the block is a continuation of the thought, as in, use this command to do something interesting:
```
   $ interestingcommand --parameter=27
```
Alternatively, the preceding sentence should end with a period (i.e., ". ::") 

Looking through, for example, all the Yocto Project documents, I find an ending ":" is typically used and occasionally an ending period. We shouldn't end the sentence without any punctuation.

**Comment by dbkinder** [comment]
I can go through all the documents to make this consistent, and document this in our documentation guidelines.  My vote is to have the preceding sentence before a block end with a colon (so using ": ::")

**Comment by gvancuts** [comment]
The "::" right at the end of the entence will give you a single ':' ending it, it's a fully minimized version of ": ::" (although I agree the latter is more intuitive and user-friendly)


-------- Original message --------

**Comment by dbkinder** [comment]
I didn't know about the difference between having and not having a space before the trailing "::" so I'll consider myself educated.  Thanks. Bottom line is that we want some punctuation at the end of these lines so I'll do a quick check.

**Comment by dbkinder** [comment]
I scanned (again) for odd looking lines with :: on them and fixed and verified we don't have any more trailing lines in the generated documents with "::"

**Comment by dbkinder** [comment]
@pohly it would be nice, but not critical to get this into the 1.0 documentation release

**Comment by pohly** [comment]
@dbkinder The patch itself now is inconsistent: in authorized-keys.rst it uses ": ::" while in booting-and-installation.rst it uses "::".

Can we make this consistent across all documents?

My preference is for "::". It is shorter and more readable than the ": ::" where the single space is a rather subtle difference and does not "collapse" as easily into a single : when reading the .rst.

Regarding 1.0, we already have a release build, which is what is going to be tagged as 1.0. We could import all doc changes and tag that as 1.0_doc, then use that revision for the web update.

**Comment by dbkinder** [comment]
@pohly @gvancuts all the ": ::" should be "::" now.

**Comment by pohly** [comment]
@dbkinder no, I'm still seeing ": ::" in 23c9d483b, the current commit.  Can you check that you have force-pushed your revised commit?

**Comment by pohly** [comment]
@dbkinder also please rebase.

**Comment by pohly** [comment]
@dbkinder thanks, merging now.

**Comment by dbkinder** [comment]
: ::)

**Comment by pohly** [comment]
Argh 8 88)

**Pull request merged**
