### PR TITLE
Improve Ostro's security flags

### PR DESCRIPTION
**Pull request by ereshetova**
Signed-off-by: Elena Reshetova <elena.reshetova@intel.com>

### CODE REVIEW

**Comment by ereshetova** [comment]
@kad, works locally for me, flags are passed to compiler, no issues observed. In any case these are warning flags (unless you treat warnings as errors and you don't do that).

**Comment by kad** [comment]
ok to test
@ereshetova  please make sure that org membership correct on your account.

**Comment by ereshetova** [comment]
ok to test

**Comment by ereshetova** [comment]
ok to test

**Comment by ereshetova** [comment]
@kad, who is org membership?

**Comment by kad** [comment]
@ereshetova yours :) until you make your membership in 01org or in ostroproject as publicly visible, jenkins will not trigger builds for your PRs without manual approvals.

**Comment by ereshetova** [comment]
@kad, my membership is public, I belong to a number of orgs (not all of them is Intel), I checked settings, have no idea what is wrong...

**Comment by kad** [comment]
@ereshetova it's not the case. check https://help.github.com/articles/publicizing-or-hiding-organization-membership/ how to make it visible.

**Comment by ereshetova** [comment]
@kad, thank you, indeed, I was looking to the wrong tag.

**Comment by okartau** [comment]
retest this please

**Comment by mythi** [comment]
@ereshetova this is potentially tedious work but still worth trying out. However, I'd propose the commits are split in their own PRs to 'bisect' problems. Now the build stops when the first error is found. This will take many rebuild cycles to be able to spot all problems (unless you do it manually on your system first).

The first failures seem to be about java and gsignond.

**Comment by mythi** [comment]
I stand corrected. There were multiple failures last night but now all seem to be good.

**Comment by ereshetova** [comment]
Yes, failures before were due to wformat flags since it seems that some pkgs do treat all warnings as errors but haven't been tested with wformat flags. These changes are only on pic now. I have to debug the wfortmat ones separately and probably build an exception list for them. However, pic is much more important since it does provide position independent code for pkg that didn't survive pie flag.

**Comment by mythi** [comment]
@ereshetova Oh, the other commit was dropped, OK.

Could you please prefix the subject with ostro_security_flags.inc: 

The change itself looks good to me.

**Comment by ereshetova** [comment]
@mythi, done. But let's not wait for another test run because this would take the whole day again. Could you please merge this now and I will try testing another improvement today.

**Pull request merged**
