### PR TITLE
DOC: more review edits

### PR DESCRIPTION
**Pull request by dbkinder**
Cleaned up TODO items
Changed Jira references to use GitHub issues
some more formatting issues fixed

security-threat-analysis: (from Teri Oda)
- clarifying that debug modes
  could be used as an additional attack vector if not disabled in
  final products and adding debug to the out-of-scope section.
- Added bluetooth explicitly to attack surfaces

conf.py
- removed references to old jira in substition macro (not used yet)

Signed-off-by: David Kinder <david.b.kinder@intel.com>

### CODE REVIEW

**Comment by pohly** [comment]
It is too late now, but let me point out anyway that the system-and-security-architecture.rst in several places now gives the wrong impression about what Ostro supports resp. does not support.

This change was also merged without proper review.

I understand that this was deemed necessary due to time pressure, so no objections from me. But let's try to do better next time...

**Comment by dbkinder** [comment]
It's not too late. Please let us know what needs to change to give the right impression.

Rajesh was the technical reviewer for this TODO removal effort requested by marketing.

-- david kinder (Phone)

On Mar 1, 2016, at 11:11 PM, Patrick Ohly <notifications@github.com<mailto:notifications@github.com>> wrote:


It is too late now, but let me point out anyway that the system-and-security-architecture.rst in several places now gives the wrong impression about what Ostro supports resp. does not support.

This change was also merged without proper review.

I understand that this was deemed necessary due to time pressure, so no objections from me. But let's try to do better next time...

�

**Comment by pohly** [comment]
Key points where the document now has misleading information:
* EVM support is not implemented at all, all references have to be marked as "to be implemented" or be removed. In general, claiming that Ostro supports integrity protection is misleading, because the current support is known to be incomplete and insufficient for production.
* "all services except software update use systemd's ``ProtectSystem=full`` " - we have not completed this change
* "A PAM module allows root to log in without a  password." - the actual implementation is different, see how changed that in PR #7
* The list of existing groups and the corresponding resources was removed, but is relevant information that needs to be documented.
* Kernel debug interfaces are disabled in both production and development kernel (difference has not been implemented).
* SSH is not disabled in production images.

**Comment by pohly** [comment]
On Tue, 2016-03-01 at 23:23 -0800, David Kinder wrote:
> It's not too late.

Too late to review before merging...

**Comment by dbkinder** [comment]
Agree with David. It's not too late. Please provide the changes and we will do another pull but send them to us  in the next few hours so we can ensure those changes are made before it goes live.
Thanks
Sara

On Mar 1, 2016, at 11:23 PM, Kinder, David B <david.b.kinder@intel.com<mailto:david.b.kinder@intel.com>> wrote:

It's not too late. Please let us know what needs to change to give the right impression.

Rajesh was the technical reviewer for this TODO removal effort requested by marketing.

-- david kinder (Phone)

On Mar 1, 2016, at 11:11 PM, Patrick Ohly <notifications@github.com<mailto:notifications@github.com>> wrote:


It is too late now, but let me point out anyway that the system-and-security-architecture.rst in several places now gives the wrong impression about what Ostro supports resp. does not support.

This change was also merged without proper review.

I understand that this was deemed necessary due to time pressure, so no objections from me. But let's try to do better next time...

�

**Comment by pohly** [comment]
@dbkinder My proposal for removing the TODOs was and still is in PR #7. Feel free to review and merge that, or use it as base for another revision that is more aligned with marketing expectations. As I received no feedback on that PR, I don't know how I would have to enhance it.

**Comment by dbkinder** [comment]
test comment

**Pull request merged**
