### PR TITLE
add bbappends for jdk and icedtea

### PR DESCRIPTION
**Pull request by tripzero**
This should fix the build issues with the latest meta-java

### CODE REVIEW

**Comment by pohly** [comment]
There's no explanation about the problem and why this is the right solution. Also, has upstream been notified? Where? Will they merge the same change (thus making these .bbappends obsolete), or are these permanent distro-specific changes?

Has the problem I mentioned in the bug report with passing target compiler flags to the host compiler when building openjdk-8-native been fixed? Doesn't look like it.

"Fixes: IOTOS-1681" is missing.

**Comment by pohly** [comment]
If the goal is to have some distro-specific fixes while upstream also works on the problem, then meta-ostro/fixes/meta-java/recipes-devtools/ is a better place.

**Comment by tripzero** [comment]
priority one was getting build working, then deal with upstream.  I can do the opposite order if that is more desirable.

**Comment by pohly** [comment]
@tripzero hmm, have you actually tested with the latest upstream repos?

Your test build was with ostro-os master and not the CI branch. Now that I have triggered such a test build (see https://ostroproject.org/jenkins/job/ostro-os_pull-requests/960/ for https://github.com/ostroproject/ostro-os/pull/143) I'm still getting build errors for openjdk.

**Comment by pohly** [comment]
@tripzero regarding dealing with upstream: yes, please engage upstream immediately. That way we (ideally) get this change reviewed before we merge the PR.

**Comment by tripzero** [comment]
"Your test build was with ostro-os master and not the CI branch."

Yes, this test build is with ostro-os master.  I'll test these bbappends against ostro-os to test against CI.

**Comment by pohly** [comment]
@tripzero when you test against ostro-os, make sure that you check out and use the ci-upstream-monitor-master branch. Your previous test build against ostro-os was based on current master and thus would have succeeded also without your changes.

**Comment by pohly** [comment]
@tripzero I couldn't figure out what problems your .bbappends fix - they didn't have any noticable effect in my own tests. FYI, I'm currently testing two fixes on top of the CI branch which allowed me to compile OpenJDK again - see https://github.com/ostroproject/ostro-os/pull/143/commits

**Comment by tripzero** [comment]
@pohly odd.  I was able to produce a failure and a success in my local testing with my patches.

**Comment by pohly** [comment]
@tripzero do we still need these changes (if so, explain why) or can we close the PR?

**Comment by mythi** [comment]
@tripzero what's the need for this?

**Comment by tripzero** [comment]
We can close this

**Pull request closed without merging**
