### PR TITLE
unblacklist xdk-daemon

### PR DESCRIPTION
**Pull request by ipuustin**
It shouldn't depend on libarchive-bin anymore.

### CODE REVIEW

**Comment by pohly** [comment]
retest this please 

Unrelated failure (org.jenkinsci.plugins.scriptsecurity.scripts.UnapprovedUsageException).

**Comment by kad** [comment]
retest this please

**Comment by kad** [comment]
retest this please

**Comment by pohly** [comment]
@kad why was the "supported recipe" check active in build https://ostroproject.org/jenkins/job/dsl-meta-ostro_pull-requests/1513/ ?

The selftest fails because the list of supported recipes needs to be updated:
https://ostroproject.org/jenkins/job/build-recipe-selftests/1986/console

But https://github.com/ostroproject/meta-ostro/pull/186 hasn't been merged, so it shouldn't have been active, should it?

**Comment by kad** [comment]
Something bad happening with jenkins. investigating. it messes up parameters for downstream job, looks like something triggered bug in github pull request builder. :(

retest this please

**Comment by kad** [comment]
retest this please

**Comment by kad** [comment]
retest this please

**Comment by kad** [comment]
retest this please

**Comment by pohly** [comment]
Once PR #186 is merged, this PR here is not needed anymore. My preference is to merge PR #186 first.

**Comment by ipuustin** [comment]
I think we can close this. I'm keeping it open only if @kad needs this for testing Jenkins.

**Comment by kad** [comment]
no preferences from my side.

**Comment by pohly** [comment]
No longer needed, the blacklisting is gone.

**Pull request closed without merging**
