### PR TITLE
supported recipes: enhance "support" column

### PR DESCRIPTION
**Pull request by pohly**

### CODE REVIEW

**Comment by pohly** [comment]
@kad or @Valtis: okay to merge?

**Comment by Valtis** [comment]
Looks good to me, but as nitpicking and bike-shedding are my two favorite pastimes, maybe the support & recipe_supported could be renamed to supportedby and recipe_supportedby, as they no longer return boolean values.

**Comment by pohly** [comment]
@Valtis does commit 2821ace address your concern about the naming?

Okay to merge now?

**Comment by Valtis** [comment]
Ok for me.

**Comment by kad** [comment]
looks ok to me.

**Comment by pohly** [comment]
There was only one unrelated test failure on Edison, so I'm merging.

**Pull request merged**
