### PR TITLE
ostro_security_flags.inc: Adding format string flags

### PR DESCRIPTION
**Pull request by ereshetova**
Signed-off-by: Elena Reshetova <elena.reshetova@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
@ereshetova gsignond fails with these flags

@jlaako

**Comment by ereshetova** [comment]
Yes, I am trying to build a list of package exceptions and then enable it globally.

**Comment by ereshetova** [comment]
retest

**Comment by ereshetova** [comment]
retest this please

**Comment by ereshetova** [comment]
@kad, I am worried about this one: I can get it to the state that it builds and passes all the checks here, but how do I make sure all packages are rebuild with new flags? Paul just have been saying in other threads that you would need to run bitbake -c cleansstate on recipe for flag changes to start playing an effect. How is it on CI side? Is each build really a clean build without usage of any remote sstate?

**Comment by kad** [comment]
CI builds are all using sstate. Change in compilation or optimization flags in theory should trigger invalidation of the sign hash

**Comment by ereshetova** [comment]
@kad, "in theory should trigger invalidation of the sign hash" theory part is worrisome...

**Comment by ereshetova** [comment]
@mythi, @kad, ok, so tests have passed now

**Comment by mythi** [comment]
@ereshetova: @kad means we can only rely on the build system to detect it needs a full rebuild.

A comment to commit log: please add a short description what's the effect of these flags (so that people can find out without googling what they do).

(and rebase)

**Comment by ereshetova** [comment]
@mythi, comment added, rebased.

**Comment by mythi** [comment]
thanks!

**Pull request merged**
