### PR TITLE
images: cleanup image bbclasses

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
test this please

**Comment by gvancuts** [comment]
Hi @mythi , I looked briefly at this yesterday and I _think_ it does not need any other documentation changes given bmap-tools is now provided by OE-core. Specifically, can one still expect to find the tool in tmp-glibc/deploy/tools as described in doc/howtos/booting-and-installation.rst#using-bmaptool-to-create-bootable-media ?

**Comment by mythi** [comment]
@gvancuts yes, nothing changes. These are just cleanups. The only functional change is that wic removal in f4753c1

**Comment by gvancuts** [comment]
Thanks for confirming this @mythi !

**Pull request merged**
