### PR TITLE
ostro-image: Include nodejs runtime tools in full images

### PR DESCRIPTION
**Pull request by nagineni**
Include nodejs runtime tools in full images

Signed-off-by: Sudarsana Nagineni <sudarsana.nagineni@intel.com>

### CODE REVIEW

**Comment by mythi** [comment]
+1

Let's wait for the build results.

**Comment by pohly** [comment]
This needs to be rebased on top of PR #104. BUNDLE_CONTENTS[full] will no longer be in ostro-image.bbclass and the bundle had to be renamed to "world" in ostro-image-swupd.bb.

Actually, I think PR #104 already includes the nodejs-runtime-tools automatically, because now the content of the "world" bundle is derived directly from OSTRO_IMAGE_PKG_FEATURES, and that already has nodejs-runtime-tools. Previous the bundle was defined manually via a second, redundant list.

**Comment by mythi** [comment]
@nagineni I've verified this indeed gets addressed by #104 so closing this.

**Comment by nagineni** [comment]
@pohly @mythi Thanks for the update.

**Pull request closed without merging**
